### ISSUE TITLE
iOS bug: Existing photos are replaced

### ISSUE THREAD

**Issue by lucnat** [ionic-team/tutorial-photo-gallery-angular#19]
On iOS, when saving a couple of photos, closing the app, restarting and adding another photo, some of the existing ones are being replaced by the new one. 
Same problem exists in react version: https://github.com/ionic-team/photo-gallery-capacitor-react/issues/8

**Comment by dotNetkow** [comment]
I just retested the app on iOS 14 with an iPhone X and I couldn't reproduce. Can you tell me more details about how you're running the app, and what hardware you have etc? thanks.

**Comment by jcesarmobile** [comment]
closing since there was no response
